services:
  app:
    image: node:20
    command: sh -c "npm install && npm test"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: development

  test:
    image: node:20
    depends_on:
      - app